import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Imgix from 'react-imgix'
import pictureData from '../exampleApiCall'

export default function Home() {
  // console.log(pictureData[0].image_url.slice(34))

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Improve your NFT with imgix! (WEIGHT PAGE)
        </h1>

        <div className={styles.grid}>
          <div className={styles.card}>
            <p>Before</p>

            <Imgix
              src={
                'https://imgix-nft-demo-web.imgix.net/' +
                pictureData[0].image_url.slice(34)
              }
              width={200}
              height={200}
            />
            <p>File type: Jpeg</p>
            <p>Image weight: 400</p>
          </div>

          <div className={styles.card}>
            <p>After</p>
            <Imgix
              src={
                'https://imgix-nft-demo-web.imgix.net/' +
                pictureData[0].image_url.slice(34)
              }
              width={200}
              height={200}
            />
            <p>File type: Jpeg</p>
            <p>Image weight: 400</p>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

/*
Goals:
[*]Add react-imgix to app
[*]Style divs for tech info
[]Get image weight of before and after
[]Create search bar that calls API
[]Add OpenSea fanmade API call 
*/

/*
How the API works:
I created a imgix web folder source for https://lh3.googleusercontent.com.
When a person uses the OpenSea fanmade API to call a specific collection, it pulls images.
The list of images I get have the first 34 characters removed so I can just get the URL after lh3.googleusercontent.com
*/
